// Trabajo desarollado por: Facundo Esquivel (306504) y Nyah Rüting (270931).
package interfaz;

import dominio.Entrada;
import dominio.Movimiento;
import dominio.Salida;
import dominio.ServicioAdicional;
import dominio.Sistema;
import dominio.Vehiculo;
import java.awt.BorderLayout;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class VentanaMovimiento extends javax.swing.JFrame implements Observer {

    // Referencia al sistema principal
    private Sistema sistema;

    // Ordenadores de filas para filtros a las JTables
    private TableRowSorter<DefaultTableModel> sorterMovimientosFecha;

    // Modelos para ComboBox y Table
    private DefaultTableModel modeloTblMovimientos;

    public VentanaMovimiento(Sistema unSistema, LocalDate fecha, LocalTime desde, LocalTime hasta) {

        // Establece titulo
        setTitle("Movimientos del " + fecha + " [" + desde + " - " + hasta + "]");
        setSize(700, 400);
        setLayout(new BorderLayout());

        sistema = unSistema;
        sistema.addObserver(this);

        // Inicializa componentes
        initComponents();

        // Aplica tema general
        actualizarColor();

        // Obtiene Movimientos del rango especificado
        List<Movimiento> filtrados = sistema.obtenerMovimientosPorRango(fecha, desde, hasta);

        // Asocia el sorter a la tabla de movimientos para permitir filtrado
        modeloTblMovimientos = (DefaultTableModel) tblMovimientos.getModel();
        sorterMovimientosFecha = new TableRowSorter<>(modeloTblMovimientos);
        tblMovimientos.setRowSorter(sorterMovimientosFecha);
        sorterMovimientosFecha.setSortKeys(List.of(new RowSorter.SortKey(0, SortOrder.ASCENDING)));

        // Guardamos las matriculas en las listas
        Set<String> matriculas = new TreeSet<>();

        for (Movimiento m : filtrados) {
            String tipo = m.getClass().getSimpleName();
            String matricula = "N/A";

            // Obtiene matricula dependiendo del objeto
            if (m instanceof Entrada) {
                Vehiculo v = ((Entrada) m).getVehiculo();
                if (v != null) {
                    matricula = v.getMatricula();
                }
            } else if (m instanceof Salida) {
                Entrada entrada = ((Salida) m).getEntrada();
                if (entrada != null && entrada.getVehiculo() != null) {
                    matricula = entrada.getVehiculo().getMatricula();
                }
            } else if (m instanceof ServicioAdicional) {
                Vehiculo v = ((ServicioAdicional) m).getVehiculo();
                if (v != null) {
                    matricula = v.getMatricula();
                }
            }

            // Corrige nombre de Servicio Adicional porque a Nyah le molesta
            if (tipo.equals("ServicioAdicional")) {
                tipo = "Servicio Adicional";
            }

            LocalDateTime fechaHoraMovimiento = m.getFechaHora();
            modeloTblMovimientos.addRow(new Object[]{
                fechaHoraMovimiento,
                tipo,
                matricula
            });

            // Agrega Matricula
            matriculas.add(matricula);
        }

        // Asigna Matriculas a ComboList
        cmbMatricula.addItem("Todos");
        for (String mat : matriculas) {
            cmbMatricula.addItem(mat);
        }

    }

    public void aplicarFiltro() {
        List<RowFilter<Object, Object>> filtros = new ArrayList<>();
        if (!cmbTipo.getSelectedItem().equals("Todos")) {
            filtros.add(RowFilter.regexFilter("^" + cmbTipo.getSelectedItem() + "$", 1));
        }
        if (!cmbMatricula.getSelectedItem().equals("Todos")) {
            filtros.add(RowFilter.regexFilter("^" + cmbMatricula.getSelectedItem() + "$", 2));
        }
        sorterMovimientosFecha.setRowFilter(filtros.isEmpty() ? null : RowFilter.andFilter(filtros));
    }

    public void actualizarColor() {
        ColoresFondo.aplicarTema(this.getContentPane(), sistema.esTemaOscuro());
    }

    /**
     This method is called from within the constructor to initialize the form.
     WARNING: Do NOT modify this code. The content of this method is always
     regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovimientos = new javax.swing.JTable();
        lblMatricula = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        cmbMatricula = new javax.swing.JComboBox<>();
        cmbTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        tblMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha y Hora", "Tipo de Movimiento", "Matricula"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMovimientos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(6, 106, 804, 365);

        lblMatricula.setText("Matricula");
        getContentPane().add(lblMatricula);
        lblMatricula.setBounds(30, 40, 90, 20);

        lblTipo.setText("Tipo de Movimiento");
        getContentPane().add(lblTipo);
        lblTipo.setBounds(400, 40, 108, 20);

        cmbMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMatriculaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbMatricula);
        cmbMatricula.setBounds(120, 40, 150, 22);

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Entrada", "Salida", "Servicio Adicional" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTipo);
        cmbTipo.setBounds(540, 40, 160, 22);

        setSize(new java.awt.Dimension(824, 514));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        aplicarFiltro();
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void cmbMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMatriculaActionPerformed
        aplicarFiltro();
    }//GEN-LAST:event_cmbMatriculaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbMatricula;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTable tblMovimientos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object ob) {
        actualizarColor();
    }
}
